//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE.PID.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AE.PID.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_clear_validation_marks {
            get {
                object obj = ResourceManager.GetObject("ICON_clear_validation_marks", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_edit_configuration {
            get {
                object obj = ResourceManager.GetObject("ICON_edit_configuration", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_format_page {
            get {
                object obj = ResourceManager.GetObject("ICON_format_page", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_help {
            get {
                object obj = ResourceManager.GetObject("ICON_help", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_insert_legend {
            get {
                object obj = ResourceManager.GetObject("ICON_insert_legend", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_load_libraries {
            get {
                object obj = ResourceManager.GetObject("ICON_load_libraries", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_open_export_tool {
            get {
                object obj = ResourceManager.GetObject("ICON_open_export_tool", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_open_select_tool {
            get {
                object obj = ResourceManager.GetObject("ICON_open_select_tool", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_update_document {
            get {
                object obj = ResourceManager.GetObject("ICON_update_document", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_validate_designation_unique {
            get {
                object obj = ResourceManager.GetObject("ICON_validate_designation_unique", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_validate_master_exist {
            get {
                object obj = ResourceManager.GetObject("ICON_validate_master_exist", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Log_ {
            get {
                return ResourceManager.GetString("Log_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除成功。.
        /// </summary>
        public static string MSG_delete_tmp_files_completed {
            get {
                return ResourceManager.GetString("MSG_delete_tmp_files_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到文档模具与库中模具不一致，是否立即更新文档模具？.
        /// </summary>
        public static string MSG_document_masters_update_confirmation {
            get {
                return ResourceManager.GetString("MSG_document_masters_update_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文档已经准备好更新。.
        /// </summary>
        public static string MSG_document_ready_for_update {
            get {
                return ResourceManager.GetString("MSG_document_ready_for_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到思源黑体，请确认安装完成后重启Visio。.
        /// </summary>
        public static string MSG_font_not_found {
            get {
                return ResourceManager.GetString("MSG_font_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经是最新版。.
        /// </summary>
        public static string MSG_no_valid_update {
            get {
                return ResourceManager.GetString("MSG_no_valid_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性 {0} 对于形状 {1} 已经有用户定义的值：{2}。您是否希望使用新值 {3} 覆盖它？{4}点击 &apos;是&apos; 覆盖该值，或点击 &apos;否&apos; 保留当前值。.
        /// </summary>
        public static string MSG_property_value_override_confirmation {
            get {
                return ResourceManager.GetString("MSG_property_value_override_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法连接至服务器，请检查网络：{0}。.
        /// </summary>
        public static string MSG_server_connect_failed_with_message {
            get {
                return ResourceManager.GetString("MSG_server_connect_failed_with_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功。.
        /// </summary>
        public static string MSG_update_completed {
            get {
                return ResourceManager.GetString("MSG_update_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新失败：{0}。.
        /// </summary>
        public static string MSG_update_failed_with_message {
            get {
                return ResourceManager.GetString("MSG_update_failed_with_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找到更新工具，路径{0}。.
        /// </summary>
        public static string MSG_update_tool_found_at {
            get {
                return ResourceManager.GetString("MSG_update_tool_found_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法写入数据，文件被占用：{0}。.
        /// </summary>
        public static string MSG_write_file_failed_with_message {
            get {
                return ResourceManager.GetString("MSG_write_file_failed_with_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE PID.
        /// </summary>
        public static string PROPERTY_product_name {
            get {
                return ResourceManager.GetString("PROPERTY_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TEMPLATE_parts_list {
            get {
                object obj = ResourceManager.GetObject("TEMPLATE_parts_list", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
