//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE.PID.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AE.PID.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BOM_template {
            get {
                object obj = ResourceManager.GetObject("BOM_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon edit_configuration {
            get {
                object obj = ResourceManager.GetObject("edit_configuration", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon format_page {
            get {
                object obj = ResourceManager.GetObject("format_page", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon load_libraries {
            get {
                object obj = ResourceManager.GetObject("load_libraries", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- XSD manual extracted from package NLog.Schema: https://www.nuget.org/packages/NLog.Schema--&gt;
        ///&lt;nlog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://www.nlog-project.org/schemas/NLog.xsd&quot;
        ///      xsi:schemaLocation=&quot;&quot;
        ///      autoReload=&quot;true&quot;
        ///      internalLogFile=&quot;c:\temp\console-example-internal.log&quot;
        ///      internalLogLevel=&quot;Info&quot;&gt;
        ///
        ///    &lt;!-- the targets to write to --&gt;
        ///    &lt;targets&gt;
        ///        &lt;!-- write logs to file --&gt;
        ///        &lt;target xs [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NLog_config {
            get {
                return ResourceManager.GetString("NLog_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon open_export_tool {
            get {
                object obj = ResourceManager.GetObject("open_export_tool", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE.PID.
        /// </summary>
        public static string Product_name {
            get {
                return ResourceManager.GetString("Product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性 {0} 对于形状 {1} 已经有用户定义的值：{2}。您是否希望使用新值 {3} 覆盖它？{4}点击 &apos;是&apos; 覆盖该值，或点击 &apos;否&apos; 保留当前值。.
        /// </summary>
        public static string Property_Value_Override_Confirmation {
            get {
                return ResourceManager.GetString("Property_Value_Override_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon update_document {
            get {
                object obj = ResourceManager.GetObject("update_document", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
