//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE.PID.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AE.PID.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_clear_validation_marks {
            get {
                object obj = ResourceManager.GetObject("ICON_clear_validation_marks", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_edit_configuration {
            get {
                object obj = ResourceManager.GetObject("ICON_edit_configuration", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_format_page {
            get {
                object obj = ResourceManager.GetObject("ICON_format_page", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_help {
            get {
                object obj = ResourceManager.GetObject("ICON_help", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_insert_legend {
            get {
                object obj = ResourceManager.GetObject("ICON_insert_legend", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_load_libraries {
            get {
                object obj = ResourceManager.GetObject("ICON_load_libraries", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_open_export_tool {
            get {
                object obj = ResourceManager.GetObject("ICON_open_export_tool", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_open_select_tool {
            get {
                object obj = ResourceManager.GetObject("ICON_open_select_tool", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_update_document {
            get {
                object obj = ResourceManager.GetObject("ICON_update_document", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_validate_designation_unique {
            get {
                object obj = ResourceManager.GetObject("ICON_validate_designation_unique", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon ICON_validate_master_exist {
            get {
                object obj = ResourceManager.GetObject("ICON_validate_master_exist", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Log_ {
            get {
                return ResourceManager.GetString("Log_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除成功。 的本地化字符串。
        /// </summary>
        public static string MSG_delete_tmp_files_completed {
            get {
                return ResourceManager.GetString("MSG_delete_tmp_files_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到文档模具与库中模具不一致，是否立即更新文档模具？ 的本地化字符串。
        /// </summary>
        public static string MSG_document_masters_update_confirmation {
            get {
                return ResourceManager.GetString("MSG_document_masters_update_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档已经准备好更新。 的本地化字符串。
        /// </summary>
        public static string MSG_document_ready_for_update {
            get {
                return ResourceManager.GetString("MSG_document_ready_for_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到思源黑体，请确认安装完成后重启Visio。 的本地化字符串。
        /// </summary>
        public static string MSG_font_not_found {
            get {
                return ResourceManager.GetString("MSG_font_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是最新版。 的本地化字符串。
        /// </summary>
        public static string MSG_no_valid_update {
            get {
                return ResourceManager.GetString("MSG_no_valid_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 {0} 对于形状 {1} 已经有用户定义的值：{2}。您是否希望使用新值 {3} 覆盖它？{4}点击 &apos;是&apos; 覆盖该值，或点击 &apos;否&apos; 保留当前值。 的本地化字符串。
        /// </summary>
        public static string MSG_property_value_override_confirmation {
            get {
                return ResourceManager.GetString("MSG_property_value_override_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接至服务器，请检查网络：{0}。 的本地化字符串。
        /// </summary>
        public static string MSG_server_connect_failed_with_message {
            get {
                return ResourceManager.GetString("MSG_server_connect_failed_with_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功。 的本地化字符串。
        /// </summary>
        public static string MSG_update_completed {
            get {
                return ResourceManager.GetString("MSG_update_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败：{0}。 的本地化字符串。
        /// </summary>
        public static string MSG_update_failed_with_message {
            get {
                return ResourceManager.GetString("MSG_update_failed_with_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找到更新工具，路径{0}。 的本地化字符串。
        /// </summary>
        public static string MSG_update_tool_found_at {
            get {
                return ResourceManager.GetString("MSG_update_tool_found_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法写入数据，文件被占用：{0}。 的本地化字符串。
        /// </summary>
        public static string MSG_write_file_failed_with_message {
            get {
                return ResourceManager.GetString("MSG_write_file_failed_with_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AE PID 的本地化字符串。
        /// </summary>
        public static string PROPERTY_product_name {
            get {
                return ResourceManager.GetString("PROPERTY_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TEMPLATE_parts_list {
            get {
                object obj = ResourceManager.GetObject("TEMPLATE_parts_list", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
